model:
  path: "./model.pth"
  classes: ['fist', 'five', 'one', 'other', 'two']

inference:
  stream_url: "http://127.0.0.1:8080/live.m3u8"

ui:
  window_name: "Hand Detection System"
  display_width: 960